name: Node.js CI
on:
  pull_request:
    branches:
      - master
      - assignment2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm install --only=dev --no-shrinkwrap
    - run: npm run build --if-present
    - run: npm test